#!/usr/bin/env python3
"""
Kiacha OS Asset Embedding Tool

This script prepares frontend assets for embedding into the Tauri binary.
It creates a Rust module that includes all assets using include_bytes!()

Usage:
    python embed_assets.py
    
    This will:
    1. Read the frontend dist/ directory
    2. Generate Rust code with embedded assets
    3. Create src-tauri/src/embed/assets.rs
"""

import os
import sys
from pathlib import Path

def get_mime_type(filename):
    """Determine MIME type from filename"""
    ext = Path(filename).suffix.lower()
    mime_types = {
        '.html': 'text/html; charset=utf-8',
        '.css': 'text/css; charset=utf-8',
        '.js': 'application/javascript; charset=utf-8',
        '.json': 'application/json; charset=utf-8',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.gif': 'image/gif',
        '.svg': 'image/svg+xml',
        '.wasm': 'application/wasm',
        '.ttf': 'font/ttf',
        '.woff': 'font/woff',
        '.woff2': 'font/woff2',
        '.txt': 'text/plain; charset=utf-8',
        '.md': 'text/markdown; charset=utf-8',
    }
    return mime_types.get(ext, 'application/octet-stream')

def escape_path(path):
    """Escape path for Rust code"""
    return path.replace('\\', '/')

def generate_embed_module():
    """Generate Rust code that embeds frontend assets"""
    
    dist_dir = Path(__file__).parent / 'dist'
    
    if not dist_dir.exists():
        print(f"Warning: dist/ directory not found at {dist_dir}")
        print("Frontend assets will not be embedded.")
        print("Run 'npm run build' in the frontend directory first.")
        return False
    
    print(f"[*] Scanning {dist_dir} for assets...")
    
    # Collect all files
    files = []
    for root, dirs, filenames in os.walk(dist_dir):
        for filename in filenames:
            full_path = Path(root) / filename
            rel_path = full_path.relative_to(dist_dir)
            files.append((rel_path, full_path))
    
    if not files:
        print("No files found in dist/")
        return False
    
    print(f"[*] Found {len(files)} files to embed")
    
    # Generate Rust code
    rust_code = '''/// Auto-generated embedded assets
/// Generated by embed_assets.py

use std::collections::HashMap;

pub struct EmbeddedAssets {
    pub files: HashMap<&'static str, (&'static [u8], &'static str)>,
}

impl EmbeddedAssets {
    pub fn new() -> Self {
        let mut files = HashMap::new();
        
'''
    
    for rel_path, full_path in sorted(files):
        escaped_path = escape_path(str(rel_path))
        mime_type = get_mime_type(str(rel_path))
        
        # Use include_bytes! for binary files
        rust_code += f'''        files.insert(
            "{escaped_path}",
            (include_bytes!("{full_path}"), "{mime_type}"),
        );
        
'''
    
    rust_code += '''        EmbeddedAssets { files }
    }
    
    pub fn get(&self, path: &str) -> Option<(&'static [u8], &'static str)> {
        self.files.get(path).copied()
    }
}
'''
    
    # Write to file
    output_path = Path(__file__).parent / 'src-tauri' / 'src' / 'embed' / 'assets.rs'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write(rust_code)
    
    print(f"[✓] Generated {output_path}")
    return True

if __name__ == '__main__':
    if generate_embed_module():
        print("\n[✓] Asset embedding complete!")
        sys.exit(0)
    else:
        print("\n[!] Asset embedding skipped (frontend not built yet)")
        sys.exit(0)
